// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Categorypage documents */
interface CategoryPageDocumentData {
  /**
   * Category Name field in *Categorypage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category-page.category_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  category_name: prismicT.RichTextField;
  /**
   * Category Desc field in *Categorypage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category-page.category_desc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  category_desc: prismicT.KeyTextField;
  /**
   * Meta Title field in *Categorypage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category-page.metaTitle
   * - **Tab**: SEO Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  metaTitle: prismicT.KeyTextField;
  /**
   * Meta Description field in *Categorypage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category-page.metaDescription
   * - **Tab**: SEO Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  metaDescription: prismicT.KeyTextField;
  /**
   * Social Cards field in *Categorypage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: category-page.socialCards[]
   * - **Tab**: SEO Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  socialCards: prismicT.GroupField<
    Simplify<CategoryPageDocumentDataSocialCardsItem>
  >;
}
/**
 * Item in Categorypage → Social Cards
 *
 */
export interface CategoryPageDocumentDataSocialCardsItem {
  /**
   * Social Card Image field in *Categorypage → Social Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category-page.socialCards[].socialCardImage
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  socialCardImage: prismicT.ImageField<never>;
  /**
   * Social Card Title field in *Categorypage → Social Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category-page.socialCards[].socialCardTitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  socialCardTitle: prismicT.KeyTextField;
  /**
   * Social Card Description field in *Categorypage → Social Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category-page.socialCards[].socialCardDescription
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  socialCardDescription: prismicT.KeyTextField;
}
/**
 * Categorypage document from Prismic
 *
 * - **API ID**: `category-page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryPageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<CategoryPageDocumentData>,
    "category-page",
    Lang
  >;
/** Content for Homepage documents */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home-page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<HomePageDocumentDataSlicesSlice>;
  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home-page.metaTitle
   * - **Tab**: SEO Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  metaTitle: prismicT.KeyTextField;
  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home-page.metaDescription
   * - **Tab**: SEO Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  metaDescription: prismicT.KeyTextField;
  /**
   * Social Cards Facebook & Twitter field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home-page.socialCards[]
   * - **Tab**: SEO Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  socialCards: prismicT.GroupField<
    Simplify<HomePageDocumentDataSocialCardsItem>
  >;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomePageDocumentDataSlicesSlice =
  | HomepageHeroSlice
  | SingleHighlightedCategorySectionSlice
  | TopCategoriesSectionSlice;
/**
 * Item in Homepage → Social Cards Facebook & Twitter
 *
 */
export interface HomePageDocumentDataSocialCardsItem {
  /**
   * Social Card Image field in *Homepage → Social Cards Facebook & Twitter*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home-page.socialCards[].socialCardImage
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  socialCardImage: prismicT.ImageField<never>;
  /**
   * Social Card Title field in *Homepage → Social Cards Facebook & Twitter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home-page.socialCards[].socialCardTitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  socialCardTitle: prismicT.KeyTextField;
  /**
   * Social Card Description field in *Homepage → Social Cards Facebook & Twitter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home-page.socialCards[].socialCardDescription
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  socialCardDescription: prismicT.KeyTextField;
}
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `home-page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home-page",
    Lang
  >;
/** Content for Menu documents */
interface MenuDocumentData {
  /**
   * Menu Title field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menuTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  menuTitle: prismicT.KeyTextField;
  /**
   * Menu Links field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  menu_links: prismicT.GroupField<Simplify<MenuDocumentDataMenuLinksItem>>;
}
/**
 * Item in Menu → Menu Links
 *
 */
export interface MenuDocumentDataMenuLinksItem {
  /**
   * Menu Item Name field in *Menu → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_links[].menuItemName
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  menuItemName: prismicT.KeyTextField;
  /**
   * Menu Item Description field in *Menu → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_links[].menuItemDesc
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  menuItemDesc: prismicT.KeyTextField;
  /**
   * Menu Item Link field in *Menu → Menu Links*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_links[].menuItemLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  menuItemLink: prismicT.RelationField<"category-page">;
}
/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;
/** Content for Longreadpage documents */
interface PageDocumentData {
  /**
   * Meta Title field in *Longreadpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: My title for Search Engine
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismicT.KeyTextField;
  /**
   * Meta Description field in *Longreadpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The description that will appear in search engine
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismicT.KeyTextField;
  /**
   * Social Cards - Facebook & Twitter field in *Longreadpage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page.social_cards[]
   * - **Tab**: SEO Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  social_cards: prismicT.GroupField<Simplify<PageDocumentDataSocialCardsItem>>;
}
/**
 * Item in Longreadpage → Social Cards - Facebook & Twitter
 *
 */
export interface PageDocumentDataSocialCardsItem {
  /**
   * Social Card Image field in *Longreadpage → Social Cards - Facebook & Twitter*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.social_cards[].social_card_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  social_card_image: prismicT.ImageField<never>;
  /**
   * Social Card Title field in *Longreadpage → Social Cards - Facebook & Twitter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.social_cards[].social_card_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  social_card_title: prismicT.KeyTextField;
  /**
   * Social card description field in *Longreadpage → Social Cards - Facebook & Twitter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.social_cards[].social_card_description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  social_card_description: prismicT.KeyTextField;
}
/**
 * Longreadpage document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Storypage documents */
interface StoryPageDocumentData {
  /**
   * Title field in *Storypage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story-page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Category field in *Storypage*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: story-page.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  category: prismicT.RelationField<"category-page">;
  /**
   * Slice Zone field in *Storypage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: story-page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<StoryPageDocumentDataSlicesSlice>;
  /**
   * Meta Title field in *Storypage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story-page.metaTitle
   * - **Tab**: SEO Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  metaTitle: prismicT.KeyTextField;
  /**
   * Meta Description field in *Storypage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story-page.metaDescription
   * - **Tab**: SEO Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  metaDescription: prismicT.KeyTextField;
  /**
   * Social Cards - Facebook & Twitter field in *Storypage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: story-page.socialCards[]
   * - **Tab**: SEO Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  socialCards: prismicT.GroupField<
    Simplify<StoryPageDocumentDataSocialCardsItem>
  >;
}
/**
 * Slice for *Storypage → Slice Zone*
 *
 */
type StoryPageDocumentDataSlicesSlice = StorySlideSlice;
/**
 * Item in Storypage → Social Cards - Facebook & Twitter
 *
 */
export interface StoryPageDocumentDataSocialCardsItem {
  /**
   * Social Card Image field in *Storypage → Social Cards - Facebook & Twitter*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story-page.socialCards[].socialCardImage
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  socialCardImage: prismicT.ImageField<never>;
  /**
   * Social Card Title field in *Storypage → Social Cards - Facebook & Twitter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story-page.socialCards[].socialCardTitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  socialCardTitle: prismicT.KeyTextField;
  /**
   * Social Card Description field in *Storypage → Social Cards - Facebook & Twitter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story-page.socialCards[].socialCardDescription
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  socialCardDescription: prismicT.KeyTextField;
}
/**
 * Storypage document from Prismic
 *
 * - **API ID**: `story-page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StoryPageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<StoryPageDocumentData>,
    "story-page",
    Lang
  >;
export type AllDocumentTypes =
  | CategoryPageDocument
  | HomePageDocument
  | MenuDocument
  | PageDocument
  | StoryPageDocument;
/**
 * Primary content in ArticleMasthead → Primary
 *
 */
interface ArticleMastheadSliceDefaultPrimary {
  /**
   * media field in *ArticleMasthead → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article_masthead.primary.media
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  media: prismicT.ImageField<"mobile" | "square">;
}
/**
 * Default variation for ArticleMasthead Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ArticleMasthead`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArticleMastheadSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<ArticleMastheadSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *ArticleMasthead*
 *
 */
type ArticleMastheadSliceVariation = ArticleMastheadSliceDefault;
/**
 * ArticleMasthead Shared Slice
 *
 * - **API ID**: `article_masthead`
 * - **Description**: `ArticleMasthead`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArticleMastheadSlice = prismicT.SharedSlice<
  "article_masthead",
  ArticleMastheadSliceVariation
>;
/**
 * Item in HomepageHero → Items
 *
 */
export interface HomepageHeroSliceDefaultItem {
  /**
   * Article field in *HomepageHero → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_hero.items[].article
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  article: prismicT.RelationField<"story-page">;
}
/**
 * Default variation for HomepageHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HomepageHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomepageHeroSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<HomepageHeroSliceDefaultItem>
>;
/**
 * Slice variation for *HomepageHero*
 *
 */
type HomepageHeroSliceVariation = HomepageHeroSliceDefault;
/**
 * HomepageHero Shared Slice
 *
 * - **API ID**: `homepage_hero`
 * - **Description**: `HomepageHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomepageHeroSlice = prismicT.SharedSlice<
  "homepage_hero",
  HomepageHeroSliceVariation
>;
/**
 * Primary content in SingleHighlightedCategorySection → Primary
 *
 */
interface SingleHighlightedCategorySectionSliceDefaultPrimary {
  /**
   * Collection Title field in *SingleHighlightedCategorySection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_highlighted_category_section.primary.collectionTitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  collectionTitle: prismicT.KeyTextField;
  /**
   * Category Link field in *SingleHighlightedCategorySection → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: single_highlighted_category_section.primary.categoryLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  categoryLink: prismicT.RelationField<"category-page">;
}
/**
 * Item in SingleHighlightedCategorySection → Items
 *
 */
export interface SingleHighlightedCategorySectionSliceDefaultItem {
  /**
   * Article field in *SingleHighlightedCategorySection → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: single_highlighted_category_section.items[].article
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  article: prismicT.RelationField<"story-page">;
}
/**
 * Default variation for SingleHighlightedCategorySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SingleHighlightedCategorySection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SingleHighlightedCategorySectionSliceDefault =
  prismicT.SharedSliceVariation<
    "default",
    Simplify<SingleHighlightedCategorySectionSliceDefaultPrimary>,
    Simplify<SingleHighlightedCategorySectionSliceDefaultItem>
  >;
/**
 * Slice variation for *SingleHighlightedCategorySection*
 *
 */
type SingleHighlightedCategorySectionSliceVariation =
  SingleHighlightedCategorySectionSliceDefault;
/**
 * SingleHighlightedCategorySection Shared Slice
 *
 * - **API ID**: `single_highlighted_category_section`
 * - **Description**: `SingleHighlightedCategorySection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SingleHighlightedCategorySectionSlice = prismicT.SharedSlice<
  "single_highlighted_category_section",
  SingleHighlightedCategorySectionSliceVariation
>;
/**
 * Item in StorySlide → Items
 *
 */
export interface StorySlideSliceDefaultItem {
  /**
   * Heading field in *StorySlide → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_slide.items[].heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismicT.KeyTextField;
  /**
   * Caption field in *StorySlide → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_slide.items[].caption
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  caption: prismicT.KeyTextField;
  /**
   * Media field in *StorySlide → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story_slide.items[].media
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  media: prismicT.ImageField<"mobile" | "square">;
  /**
   * Slide Duration field in *StorySlide → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 5
   * - **API ID Path**: story_slide.items[].slideDuration
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  slideDuration: prismicT.NumberField;
  /**
   * Thumbnail Precentage From Center field in *StorySlide → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_slide.items[].thumbnailPrecentageFromCenter
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  thumbnailPrecentageFromCenter: prismicT.KeyTextField;
}
/**
 * Default variation for StorySlide Slice
 *
 * - **API ID**: `default`
 * - **Description**: `StorySlide`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StorySlideSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<StorySlideSliceDefaultItem>
>;
/**
 * Slice variation for *StorySlide*
 *
 */
type StorySlideSliceVariation = StorySlideSliceDefault;
/**
 * StorySlide Shared Slice
 *
 * - **API ID**: `story_slide`
 * - **Description**: `StorySlide`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StorySlideSlice = prismicT.SharedSlice<
  "story_slide",
  StorySlideSliceVariation
>;
/**
 * Primary content in TopCategoriesSection → Primary
 *
 */
interface TopCategoriesSectionSliceDefaultPrimary {
  /**
   * Section Title field in *TopCategoriesSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_categories_section.primary.sectionTitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  sectionTitle: prismicT.KeyTextField;
}
/**
 * Item in TopCategoriesSection → Items
 *
 */
export interface TopCategoriesSectionSliceDefaultItem {
  /**
   * Category Thumbnail field in *TopCategoriesSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: top_categories_section.items[].categoryThumbnail
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  categoryThumbnail: prismicT.ImageField<never>;
  /**
   * Category Name field in *TopCategoriesSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_categories_section.items[].categoryName
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  categoryName: prismicT.KeyTextField;
  /**
   * Category Link field in *TopCategoriesSection → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: top_categories_section.items[].categoryLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  categoryLink: prismicT.RelationField<"category-page">;
}
/**
 * Default variation for TopCategoriesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TopCategoriesSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TopCategoriesSectionSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<TopCategoriesSectionSliceDefaultPrimary>,
  Simplify<TopCategoriesSectionSliceDefaultItem>
>;
/**
 * Slice variation for *TopCategoriesSection*
 *
 */
type TopCategoriesSectionSliceVariation = TopCategoriesSectionSliceDefault;
/**
 * TopCategoriesSection Shared Slice
 *
 * - **API ID**: `top_categories_section`
 * - **Description**: `TopCategoriesSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TopCategoriesSectionSlice = prismicT.SharedSlice<
  "top_categories_section",
  TopCategoriesSectionSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      CategoryPageDocumentData,
      CategoryPageDocumentDataSocialCardsItem,
      CategoryPageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      HomePageDocumentDataSocialCardsItem,
      HomePageDocument,
      MenuDocumentData,
      MenuDocumentDataMenuLinksItem,
      MenuDocument,
      PageDocumentData,
      PageDocumentDataSocialCardsItem,
      PageDocument,
      StoryPageDocumentData,
      StoryPageDocumentDataSlicesSlice,
      StoryPageDocumentDataSocialCardsItem,
      StoryPageDocument,
      AllDocumentTypes,
      ArticleMastheadSliceDefaultPrimary,
      ArticleMastheadSliceDefault,
      ArticleMastheadSliceVariation,
      ArticleMastheadSlice,
      HomepageHeroSliceDefaultItem,
      HomepageHeroSliceDefault,
      HomepageHeroSliceVariation,
      HomepageHeroSlice,
      SingleHighlightedCategorySectionSliceDefaultPrimary,
      SingleHighlightedCategorySectionSliceDefaultItem,
      SingleHighlightedCategorySectionSliceDefault,
      SingleHighlightedCategorySectionSliceVariation,
      SingleHighlightedCategorySectionSlice,
      StorySlideSliceDefaultItem,
      StorySlideSliceDefault,
      StorySlideSliceVariation,
      StorySlideSlice,
      TopCategoriesSectionSliceDefaultPrimary,
      TopCategoriesSectionSliceDefaultItem,
      TopCategoriesSectionSliceDefault,
      TopCategoriesSectionSliceVariation,
      TopCategoriesSectionSlice,
    };
  }
}
