// Code generated by Slice Machine. DO NOT EDIT.

import ArticleMasthead from './ArticleMasthead';
import HomepageHero from './HomepageHero';
import SingleHighlightedCategorySection from './SingleHighlightedCategorySection';
import StorySlide from './StorySlide';
import TopCategoriesSection from './TopCategoriesSection';

export {
	ArticleMasthead,
	HomepageHero,
	SingleHighlightedCategorySection,
	StorySlide,
	TopCategoriesSection,
};

export const components = {
	article_masthead: ArticleMasthead,
	homepage_hero: HomepageHero,
	single_highlighted_category_section: SingleHighlightedCategorySection,
	story_slide: StorySlide,
	top_categories_section: TopCategoriesSection,
};
