// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  homepage_hero: dynamic(() => import("./HomepageHero")),
  media_columns: dynamic(() => import("./MediaRow")),
  single_highlighted_category_section: dynamic(
    () => import("./SingleHighlightedCategorySection")
  ),
  story_slide: dynamic(() => import("./StorySlide")),
  text_row: dynamic(() => import("./TextRow")),
  top_categories_section: dynamic(() => import("./TopCategoriesSection")),
};
