// This file is generated by Slice Machine. Update with care!

import HomepageHero from './HomepageHero';
import SingleHighlightedCategorySection from './SingleHighlightedCategorySection';
import TopCategoriesSection from './TopCategoriesSection';

export {
	HomepageHero,
	SingleHighlightedCategorySection,
	TopCategoriesSection,
};

export const components = {
	homepage_hero: HomepageHero,
	single_highlighted_category_section: SingleHighlightedCategorySection,
	top_categories_section: TopCategoriesSection,
};
